apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-service.fullname" . }}
  labels:
    app: {{ include "cloud-service.name" . }}
    chart: {{ include "cloud-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-service.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-service.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ include "cloud-service.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
          resources: {{ toYaml .Values.resources | indent 12 }}