apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-service
  template:
    metadata:
      labels:
        app: cloud-service
    spec:
      containers:
      - name: server
        image: venkatesh559/cloud-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
