replicaCount: 2

image:
  repository: venkatesh559/cloud-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}